name: imtihon_4oyuchun
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  bloc_concurrency: ^0.2.5
  equatable: ^2.0.5
  firebase_core: ^3.2.0
  firebase_storage: ^12.1.1
  flutter_local_notifications: ^17.2.1+1
  google_maps_flutter: ^2.7.0
  yandex_mapkit: ^4.1.0
  http: ^1.2.1
  flutter_svg: ^2.0.10+1
  cloud_firestore: ^5.1.0
  firebase_auth: ^5.1.2
  permission_handler: ^11.3.1
  lottie: ^2.0.0
  anim_search_bar: ^2.0.3
  vertical_card_pager: ^1.6.2
  geolocator: ^12.0.0
  image_picker: ^1.1.2
  gap: ^3.0.1
  firebase_messaging: ^15.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/