// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgQBjYI_ztEz_vQUtXtUFCGrgOZ22pSn0',
    appId: '1:921183468666:web:0a2a175d9a30fc54654fc3',
    messagingSenderId: '921183468666',
    projectId: 'mening-4oy-imtihonim',
    authDomain: 'mening-4oy-imtihonim.firebaseapp.com',
    storageBucket: 'mening-4oy-imtihonim.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMyRA65n4vRfvZE2jOnAcJOXpYH4lz8Mk',
    appId: '1:921183468666:android:e3d6977049fbc3bd654fc3',
    messagingSenderId: '921183468666',
    projectId: 'mening-4oy-imtihonim',
    storageBucket: 'mening-4oy-imtihonim.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqdHgNRGj2vL-6KScQHStUH-D3ETEdRQ4',
    appId: '1:921183468666:ios:d5d1b5d2aea7cdbd654fc3',
    messagingSenderId: '921183468666',
    projectId: 'mening-4oy-imtihonim',
    storageBucket: 'mening-4oy-imtihonim.appspot.com',
    iosBundleId: 'com.example.imtihon4oyuchun',
  );
}
